apiVersion: v1
kind: Service
metadata:
  labels:
    app: easytravel
    tier: web
  name: easytravel-www
  namespace: easytravel
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: easytravel
    tier: web
  type: LoadBalancer


